name: Node.js Package

on:
  pull_request:
    branches: [develop]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
         args: '.'
      - name: lint
        run: "npm run lint"

#  Sonar-scanner:
#    if: ${{ github.event_name == 'pull_request' }}
#    name: Sonar Scanner
#    runs-on: ubuntu-latest 
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Code Scanner
#        uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
